name:                multi-dijkstra
version:             0.1.0.0
github:              "tyehle/multi-dijkstra"
license:             MIT
author:              "Tobin Yehle"
maintainer:          "tobinyehlee@gmail.com"
copyright:           "2019 Tobin Yehle"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/tyehle/multi-dijkstra#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - containers
    - PSQueue

executables:
  multi-dijkstra-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - multi-dijkstra

tests:
  multi-dijkstra-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - multi-dijkstra
